### ISSUE TITLE
ldap

### ISSUE THREAD

**Issue by kevin249** [witersen/SvnAdminV2.0#13]
求问支持LDAP得版本2.4得发布时间？
谢谢

**Comment by witersen** [comment]
ldap功能开发中，此功能为2.3.4发布之前开发的最后模块，完成后就会发正式包和更新包。预估时间本周结束内。

**Comment by witersen** [comment]
2.3.4测试版本已发布，可以体验下，看有无改进意见。有问题可加群讨论。

**Comment by kevin249** [comment]
好的 谢谢  先试试  请问讨论群位置？

**Comment by witersen** [comment]
github主页也有介绍，是QQ群 平时讨论技术点比较多 633108141
