### ISSUE TITLE
svn端口修改无作用

### ISSUE THREAD

**Issue by kksay2010** [witersen/SvnAdminV2.0#18]
我修改了容器对应端口：docker run -d -p 9001:80 -p 3690:3690 \****************
                   
                                容器端口：80      3690
                   服务器映射端口：9001    3690

然后我在系统设置中修改web端口
![1](https://user-images.githubusercontent.com/29589474/222375364-d4754f33-5381-4f36-9d44-e7d37401bb53.png)

但是仓库检出还是80，且可以正常使用
![2](https://user-images.githubusercontent.com/29589474/222375462-f7970305-1975-4f67-9f8a-e63a60179cee.png)

问题来了：
1、我希望svn不开放80端口怎么设置
2、如果80端口被占用（本机未被），那么svn是否正常使用

**Comment by witersen** [comment]
注意
http://ip/xxx 等同于 http://ip:80/xxx
svn://ip/xxx 等同于 svn://ip:3690/xx

所以你的svn协议就是用的默认3690，所以这与80无关

**Comment by kksay2010** [comment]
> 

如果我想修改3690端口，是不是运行容器的命令修改一下

docker run -d -p 8-:80 -p XXXX:3690

**Comment by witersen** [comment]
是的，容器的方便之处之一，无需改动容器内的任何服务，直接修改映射参数即可。
包括修改端口、修改数据目录，都通过映射来搞就好了
