### ISSUE TITLE
svn用户登录无法获取有权限的仓库列表

### ISSUE THREAD

**Issue by MrBaoquan** [witersen/SvnAdminV2.0#19]
## 问题描述
svn管理员创建了一个测试仓库，分配权限给了svn用户xxx, xxx登陆后无法显示该仓库，登录直接报错
![image](https://user-images.githubusercontent.com/36908656/224536418-f0df0cda-69e0-48c3-ba17-3a0e4acd0515.png)

## 复现概率 (100%复现)
复现步骤
1. 开启容器
```bash
docker run -d --name svnadmintemp --privileged witersencom/svnadmin:2.5.3 /usr/sbin/init
```
2. admin登录创建repo仓库、创建用户xxx、给仓库权限分配给用户xxx
3. xxx登陆后直接报错，且没有显示repo仓库

**Comment by MrBaoquan** [comment]
svn客户端可以凭用户名/密码进行更新、提交等操作。但是web页面登录报错，不显示有权限的仓库列表

**Comment by witersen** [comment]
你好，请认真阅读文档，这个应该是 /usr/sbin/init 导致的问题：

容器启动时， 你使用 /usr/sbin/init 来覆盖掉了原本设定的启动脚本，所以会导致报错

文档中表示：【docker run -d --name svnadmintemp --privileged witersencom/svnadmin:2.5.3 /usr/sbin/init】是用来启动一个不提供服务的容器，来临时复制配置文件的

**Comment by MrBaoquan** [comment]
> 

我首先尝试了文档 3.1 docker run -d --name svnadmintemp -p 80:80 -p 3690:3690 --privileged witersencom/svnadmin:2.5.3 有这个问题，后来尝试了3.2的步骤操作，也是有同样的问题

**Comment by witersen** [comment]
你好，我刚刚 又测试了一遍，一切正常。
执行：
docker run -d --name svnadmintemp -p 80:80 -p 3690:3690 --privileged witersencom/svnadmin:2.5.3
的时候，注意你说的有问题，指的是出现了什么报错？
我猜测你是遇到了端口冲突，所以尝试下更换端口映射
如果无法解决，加首页的QQ群，我会帮你远程解决

**Comment by MrBaoquan** [comment]
> 


> 你好，我刚刚 又测试了一遍，一切正常。 执行： docker run -d --name svnadmintemp -p 80:80 -p 3690:3690 --privileged witersencom/svnadmin:2.5.3 的时候，注意你说的有问题，指的是出现了什么报错？ 我猜测你是遇到了端口冲突，所以尝试下更换端口映射 如果无法解决，加首页的QQ群，我会帮你远程解决

大佬你好，我发现问题了，确认是 "中文用户名" 会出这个问题

**Comment by witersen** [comment]
好的，解决中

**Comment by witersen** [comment]
2.5.4已解决，已发布
