### ISSUE TITLE
dav:error Could not open the requested SVN filesystem

### ISSUE THREAD

**Issue by arrheni** [witersen/SvnAdminV2.0#20]
svn路径中含有汉字报错，用浏览器和svn客户端打开都会保存，具体如下：
看起来应该不是subversive版本的问题，我猜是apache的问题？请问大佬怎么解决呢?谢谢

背景： 源码安装
系统  redhat7.6
svn，版本 1.8.19 (r1800620)
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
PHP 7.4.33 (cli) (built: Feb 14 2023 09:31:03) ( NTS )

apache日志报错：

==> /var/log/httpd/error_log <==
[Tue Apr 18 21:29:08.786715 2023] [:error] [pid 18815] (20014)Internal error: [client 10.1.2.9:64520] Can't convert string from 'UTF-8' to native encoding:
[Tue Apr 18 21:29:08.786789 2023] [:error] [pid 18815] (20014)Internal error: [client 10.1.2.9:64520] /home/svnadmin/rep/P2_P201?\\231?\\155?\\\\185?\\3?\\176/format
[Tue Apr 18 21:29:08.786807 2023] [dav:error] [pid 18815] [client 10.1.2.9:64520] Could not fetch resource information.  [500, #0]
[Tue Apr 18 21:29:08.786816 2023] [dav:error] [pid 18815] [client 10.1.2.9:64520] Could not open the requested SVN filesystem  [500, #22]
[Tue Apr 18 21:29:08.786822 2023] [dav:error] [pid 18815] [client 10.1.2.9:64520] Could not open the requested SVN filesystem  [500, #22]

==> /var/log/httpd/access_log <==
10.1.2.9 - liuw [18/Apr/2023:21:29:08 +0800] "GET /svn/P2_P201%E7%9B%91%E6%8E%A7%E5%B9%B3%E5%8F%B0/01%E5%BC%80%E5%8F%91/ HTTP/1.1" 500 235 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39"

**Comment by witersen** [comment]
你好，这个问题看起来是源码部署后，路径中带有中文导致的编码问题（Can't convert string from 'UTF-8' to native encoding:）

**Comment by witersen** [comment]
一下为个人解决思路：
首先检查机器的编码：locale
思路1：然后查看有否有未安装的编码，但是被启用了
思路2：或者通过 export LC_CTYPE="zh_CN.UTF-8" 来指定编码等等解决

**Comment by arrheni** [comment]
谢谢您！！！！您说的这个编码我也查到了，期间  设置无数次，都不生效，刚刚看了看自带的httpd service ,找到原因了
EnvironmentFile=/etc/sysconfig/httpd
在/etc/sysconfig/httpd 里居然默认配置了LANG=C，改过来就好了，哎，这个折腾我两天。玛德。

谢谢，祝老板发财
