### ISSUE TITLE
LDAP用户数超过1000时无法导入更多用户

### ISSUE THREAD

**Issue by l20f111164** [witersen/SvnAdminV2.0#24]
![image](https://user-images.githubusercontent.com/9441728/237027766-f0246652-53e5-4c52-89ad-a23aff4abde1.png)

作为专业配置管理员提一些个人建议。如上，我司LDAP用户数量大于1000，且服务器端有限制每次请求条目为1000，希望支持分页查询导入更多的LDAP用户，不然很多用户无法导入，还是没法使用。我这边使用if.svnadmin可以查询所有用户。

另外希望支持强制转换小写账号认证，多数情况下有些用户名大小不太统一，SVN本身对用户名大小写比较敏感，需要很频繁的跟同事解释去使用大小写区分去认证。

**Comment by witersen** [comment]
好的，这个问题是我疏忽了，如果有时间，可以加入首页的群聊配合测试。

**Comment by l20f111164** [comment]
好的，已加入群聊，昵称：Ven。

**Comment by witersen** [comment]
2.5.4中已解决，已发布
