### ISSUE TITLE
登录验证失效

### ISSUE THREAD

**Issue by tetejm** [witersen/SvnAdminV2.0#25]
我在系统配置->http协议检出->apache服务信息->仓库访问前缀 中默认的"/svn"改为"/"导致httpd重启后，登录界面消失，请问这个需要怎么改回来？

**Comment by witersen** [comment]
你好，修改 /etc/httpd/conf.d/subversion.conf

**Comment by witersen** [comment]
如果不行可以加首页的Q群寻求帮助
