### ISSUE TITLE
建议把定时任务中的shell执行给移除掉

### ISSUE THREAD

**Issue by 409232112** [witersen/SvnAdminV2.0#28]
这可是一个严重的安全漏洞

**Comment by witersen** [comment]
### 如果你能在不知道管理员账号密码的情况下利用这个功能实现系统破坏，那才称得上是安全漏洞。

1、【正常的功能】和【漏洞】概念上是不同的。

2、svnadmin2中的每一个接口都严格的设置了基于角色的访问权限控制。

3、定时任务的shell权限，要么是超级管理员有权限、要么是子管理员有权限。把权限开放给自己人，这个没问题。系统遭到破坏也可追溯到大致人员。

4、设计之初我已经考虑到shell执行的威力和它带来的利弊。
