### ISSUE TITLE
is it possible to integrate with Active Directory?

### ISSUE THREAD

**Issue by bibo318** [witersen/SvnAdminV2.0#29]
When integrating the results show groups that are not related to the synchronized user list.
- I see the groups that the results show are all groups without: member or memberOf

Base DN: DC=xx,DC=xx
Search filter: (&(|(objectclass=group)(objectclass=groupofnames) (objectclass=groupofuniquenames)))
Attributes: samaccountname
Groups to user attribute: memberOf
Groups to user attribute value: memberOf

**Comment by witersen** [comment]
1、Active Directory is ok to use with SVNAdmin2，many users is normal to use
2、if you have trouble about user belong group in ldap model，you can read my blog : `https://www.witersen.com/?p=1844`

**Comment by bibo318** [comment]
Thank you
