### ISSUE TITLE
一点建议，能不能增加一个基于用户或者用户组关于某一仓库下子文件夹的授权模块？

### ISSUE THREAD

**Issue by duiniwukenaihe** [witersen/SvnAdminV2.0#4]
![image](https://user-images.githubusercontent.com/15711623/163182210-e35b78ea-be9e-41e1-addf-ca5a4d9085fe.png)
参照此项目http://svn.nginxwebui.cn:6060/。生产环境还是有很多子文件夹授权的！也希望能添加导入导出备份的功能。设计上可以参考一下http://svn.nginxwebui.cn:6060/

**Comment by witersen** [comment]
感谢您的建议！
之前由于时间原因，规划的很多功能没来的开发，预计十天内有测试版出来，敬请期待啦！
