### ISSUE TITLE
浏览仓库内容时文件名乱码

### ISSUE THREAD

**Issue by cantgis** [witersen/SvnAdminV2.0#5]
![image](https://user-images.githubusercontent.com/6498032/180729265-91807d71-c7c8-4cec-b356-20165668c486.png)
![image](https://user-images.githubusercontent.com/6498032/180729319-fb3040e4-00db-4da1-a671-d7cbed7bab3a.png)
![image](https://user-images.githubusercontent.com/6498032/180729641-c770d341-d1f8-400e-99d9-40d35b7cd87c.png)

上传一个文档后，浏览仓库和配置权限  发现网页显示乱码。

使用docker仓库 svnadmin:2.3.2版本 启动

**Comment by witersen** [comment]
收到，立刻排查下问题。

**Comment by witersen** [comment]
你好，非常不好意思出现此问题。
我已经定位到问题为打包docker镜像时没有考虑到编码相关的设置问题
目前正在解决中，解决后会第一时间重新打包docker镜像并及时通知你

**Comment by witersen** [comment]
你好，非常抱歉
问题已解决，docker镜像已经修改并重新推送，版本号无变化重新拉取即可
相关的dockerfile已经更新在发行版页面可自行查看或修改构建
