### ISSUE TITLE
希望能支持passwd的导入

### ISSUE THREAD

**Issue by dragonflyings** [witersen/SvnAdminV2.0#6]
目前密码是明文存储的，希望能够兼容VisualSvnServer这种格式的passwd，导入或者加密存储。
-- 感谢作者的付出。

**Comment by witersen** [comment]
感谢你的建议
关于在使用svn协议的情况下支持passwd密文的研究我之前已经做过，并且发现不依赖http协议使用纯svn协议时对使用的passwd文件进行加密是可行的
另外我自己也想要针对VisualServer和原生格式做在线识别和批量导入，但是由于时间问题和优先级，passwd密文和批量导入的相关功能应该在2.3.x的后续放出
目前下个版本（应该是2.3.4）是关于彻底解决对svn原生功能的支持（别名、权限反转、魔力符号等）的功能，并且有可能支持sasal如ldap等

**Comment by dragonflyings** [comment]
之前用过[iF.SVNAdmin](http://www.insanefactory.com/)，界面管理很难用，你这个版本用起来就比较舒服，希望能越来越完善

**Comment by witersen** [comment]
你好，目前2.3.4版本处于公开测试阶段，可加入测试或者入群讨论功能建议。2.3.4版本除了支持ldap，加入了简单的在线用户导入功能。passwd用户加密需要配合sasl实现所以将会在2.3.4版本以后考虑支持svn协议模式用户密码密码

**Comment by witersen** [comment]
2.4.1已发布，两种协议下的密码导入已经支持。还支持http协议和svn协议同时服务和对接ldap认证。
