### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by haitao1912** [witersen/SvnAdminV2.0#7]
svnadmin2.3.3 docker镜像安装，登陆页面不显示验证码，导致登陆失败资源加载失败

**Comment by witersen** [comment]
你好，是否是先进行了容器目录挂载到宿主机之后出现的此问题呢？
不挂载目录的情况下是可正常使用的，问题出现通常为：在挂载目录后容器内文件权限受到影响
svnadmin默认使用sqlite作为数据库，当sqlite文件本身和所在目录的权限都为可写，才能正常使用
请分别在容器中为 /home/svnadmin/svnadmind.db 授权 777 和 目录 /home/svnadmin 授权 777
如果不生效，可在宿主机尝试同样的操作
reademe的faq有对应的说明
如果还无法解决可加入群聊协助解决

**Comment by haitao1912** [comment]
挂载盘在win10的D盘中，已赋予最高权限

**Comment by witersen** [comment]
请问是挂载后就不显示验证码的吗？
是否有提示报错如 验证码写入失败等提示信息
稍后我对Windows10下挂载作测试，看是否能复现问题

**Comment by haitao1912** [comment]
![Uploading C30B8FAD-A39A-44B5-91CE-E626968D2015.jpeg…]()

**Comment by haitao1912** [comment]
报错信息：出错了，请联系管理员
![Uploading 7D425C0B-75CF-4DD8-9C9F-EBB131FCD4DA.jpeg…]()

**Comment by witersen** [comment]
提前将 /home/svnadmin 目录信息复制出来到 D 盘了吗

**Comment by witersen** [comment]
我这里Windows10下挂载使用是正常的，你可以检查下是否将容器内目录信息提前复制出来了

可以参考 readme 说明：

#启动一个临时容器，并将配置文件复制出来
docker run -d \
--name svnadmintemp \
--privileged=true \
witersencom/svnadmin:2.3.3.1 \
/usr/sbin/init

#复制的数据目录为 /home/svnadmin/
cd /home/
docker cp svnadmintemp:/home/svnadmin ./

#停止并删除临时容器
dockeer stop svnadmintemp && docker rm svnadmintemp

#启动正式容器
docker run -d \
-p 80:80 \
-p 3690:3690 \
-v /home/svnadmin/:/home/svnadmin/ \
--privileged \
witersencom/svnadmin:2.3.3.1

**Comment by haitao1912** [comment]
提前复制出来了
![Uploading 57F8999E-E899-4DF4-BA95-75A9E549FC53.jpeg…]()

**Comment by witersen** [comment]
那就比较奇怪了，我这里挂载测试正常，而且我这里看不到你上传的所有图片，图片貌似是上传失败了，而且我无法帮你调试
你可以加群我帮你远程调试，或者重新上传相关图片，如 复制出来的目录结构和挂载指令

**Comment by haitao1912** [comment]
你用两天就会出问题了，我这几天都是删除容器重新创建就好了，但是用着用着就还是那样

**Comment by witersen** [comment]
所以问题是初次使用就遇到了还是使用了几天后出现才报错提示？
我现在看不到日志信息，能否在下次出现问题时让我远程帮忙调试？
我这边先用几天，看是否会出现你说的问题。

**Comment by haitao1912** [comment]
http://10.100.25.9:5001/api.php?c=Safe&a=GetVerifyOption&t=web这个url报错

**Comment by haitao1912** [comment]
几天后会有问题，我看了是http://10.100.25.9:5001/api.php?c=Safe&a=GetVerifyOption&t=web这个url报错，我这边不能联网

**Comment by haitao1912** [comment]
几天后会有问题，我看了是http://10.100.25.9:5001/api.php?c=Safe&a=GetVerifyOption&t=web这个url报错

**Comment by witersen** [comment]
好的，如果不能联网，可以把错误提示打开，这样下次出问题就会直接看到错误提示信息

步骤如下：

进入容器

取消注释文件 /var/www/html/api.php 中以下两行所在行

ini_set('display_errors', '1');
error_reporting(E_ALL);

此两行注释掉，然后正常使用即可

如果下次出现了问题，你可以在控制看到请求的url报错信息会被返回

就可以定位到是哪里抛出了异常

**Comment by witersen** [comment]
你直接 f12 打开，然后访问登录界面 
这个时候请求都会被捕获到
然后找到 api.php?c=Safe&a=GetVerifyOption&t=web 这个url 看他的返回信息是什么 
正常报错信息会作为返回直接显示

**Comment by haitao1912** [comment]
还是http://10.100.25.9:5001/api.php?c=Safe&a=GetVerifyOption&t=web这个URL报错，我看与正常的区别是Request Headers中没有cookie信息

**Comment by haitao1912** [comment]
返回为空，可以加群聊吗？我发截图

**Comment by witersen** [comment]
qq群：633108141

**Comment by witersen** [comment]
需要的报错信息是从返回看
![1](https://user-images.githubusercontent.com/47046166/188771352-5852253a-cba6-46db-bcfd-9db7cad1fadd.jpg)

**Comment by haitao1912** [comment]
我发截图了，你在群里吗？

**Comment by witersen** [comment]
我就是群主，刚才跟你说 ctrl + f5 那个，只不过你没有回复

**Comment by witersen** [comment]
你这里是请求失败了，而不是普通的 http 失败状态码，所以你先 ctrl + f5 ，看下是不是整个站点都不能访问了，如果是整个站点都无法访问，就是容器内 httpd 服务挂了

**Comment by witersen** [comment]
看下这个 response 
![2](https://user-images.githubusercontent.com/47046166/188772730-974a1533-6737-4934-987e-23917a633871.jpg)

**Comment by witersen** [comment]
此问题已有解决方案：

【原因】 
重启容器后，容器内的 httpd 由于一些原因没有成功重启 
1、构建的 docker 镜像是以 CentOS7.9.2009 为基础进行的 
由于 CentOS7.9.2009 基础镜像的权限问题：https://github.com/docker-library/docs/tree/master/centos#dockerfile-for-systemd-base-image 
导致如果启动容器时不增加 --privileged 参数 和不以 /usr/sbin/init 作为首先执行的指令，将会导致容器内一些程序无法正常启动 
2、另外不排除重启后再次启动 httpd 时由于上次的 httpd.pid 文件依然造成的识别未 httpd 运行中的误判 
【解决方案】 
如果重启容器后 web 管理系统无法访问 
只需要进入容器并执行下面的命令重新启动 httpd 服务即可 
/usr/sbin/httpd 
或者 
/usr/sbin/httpd -DFOREGROUND & 
或者
httpd
后面会考虑更换更方便的解决方案

**Comment by tomatofrommars** [comment]
> 2、另外不排除重启后再次启动 httpd 时由于上次的 httpd.pid 文件依然造成的识别未 httpd 运行中的误判

你好，我用是的2.3.3版本，部署在容器里，数据映射到了volume。
我遇到这个问题，追查到就是原因2，httpd.pid没有被及时清理导致的。现在服务器一重启，就需要重新创建container。

请问：
- 1 新的2.4版本还有容器停止后不能重启的问题吗？
- 2 如果我要升级2.4版本的话，
  - 是直接用新的镜像启动老的数据就可以吗？
  - 还是要在容器里执行这个后`cd /var/www/html/server && php install.php`，才能使用新的镜像？

**Comment by witersen** [comment]
> 

关于1
2.4.x最新版本在Linux操作系统下已经解决过此问题，目前没有用户反馈无法启动httpd的问题
2.4.x最新版本在Windows操作下偶尔由用户反馈容器内httpd无法自启动，具体原因无法定位

**Comment by witersen** [comment]
> > 2、另外不排除重启后再次启动 httpd 时由于上次的 httpd.pid 文件依然造成的识别未 httpd 运行中的误判
> 
> 你好，我用是的2.3.3版本，部署在容器里，数据映射到了volume。 我遇到这个问题，追查到就是原因2，httpd.pid没有被及时清理导致的。现在服务器一重启，就需要重新创建container。
> 
> 请问：
> 
>     * 1 新的2.4版本还有容器停止后不能重启的问题吗？
> 
>     * 2 如果我要升级2.4版本的话，
>       
>       * 是直接用新的镜像启动老的数据就可以吗？
>       * 还是要在容器里执行这个后`cd /var/www/html/server && php install.php`，才能使用新的镜像？

关于2：
2.3.x升级2.4.x主页已经有详细说明，按照说明即可，如果不确定，可在QQ群求助

**Comment by witersen** [comment]
> > 2、另外不排除重启后再次启动 httpd 时由于上次的 httpd.pid 文件依然造成的识别未 httpd 运行中的误判
> 
> 你好，我用是的2.3.3版本，部署在容器里，数据映射到了volume。 我遇到这个问题，追查到就是原因2，httpd.pid没有被及时清理导致的。现在服务器一重启，就需要重新创建container。
> 
> 请问：
> 
>     * 1 新的2.4版本还有容器停止后不能重启的问题吗？
> 
>     * 2 如果我要升级2.4版本的话，
>       
>       * 是直接用新的镜像启动老的数据就可以吗？
>       * 还是要在容器里执行这个后`cd /var/www/html/server && php install.php`，才能使用新的镜像？

关于1：
2.4.x最新版本在Linux操作系统下已经解决过此问题，目前没有用户反馈无法启动httpd的问题
2.4.x最新版本在Windows操作下偶尔由用户反馈容器内httpd无法自启动，具体原因无法定位
