### ISSUE TITLE
期待支持http

### ISSUE THREAD

**Issue by itranlin** [witersen/SvnAdminV2.0#8]

**Comment by witersen** [comment]
感谢支持
http支持很重要
目前在做的大功能为svn协议版本对ldap的支持
此功能完成后会开始支持httpd版本的开发

**Comment by devryan915** [comment]
https如果能支持就更好了

**Comment by witersen** [comment]
http协议开发中，剩余少部分代码未开发结束，预计今晚或者本周末发布支持svn协议和http自由切换的2.4版本，直接跳过2.3.4的发布

**Comment by witersen** [comment]
2.4.1已发布，http已支持，同时svn/http都支持sasl中ldap的对接认证
