### ISSUE TITLE
svnadmin使用docker安装使用两三天后容器经常起不来，需要重新创建新容器

### ISSUE THREAD

**Issue by haitao1912** [witersen/SvnAdminV2.0#9]

**Comment by witersen** [comment]
你好，请问启动不起来指的是容器本身运行中异常退出，还是容器的web服务不能提供服务？
如果是后者，可能是重启 docker 或者 重启机器后导致的 可以查看 readme 文档的第 4 条的第 11 点
如果是前者，可以提供下详细的部署操作系统类型、是否挂载目录、挂载的具体操作、系统使用流程、容器体积、容器日志等信息我这边尝试排查复现下问题

**Comment by witersen** [comment]
此问题与 issue 7 为同一问题，都是宿主机、容器、docker重启导致的，解决方案见 issue 7
